# =========================
# Namespace
# =========================
apiVersion: v1
kind: Namespace
metadata:
  name: nginx-demo
---
# =========================
# ConfigMap（設定）
# =========================
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: nginx-demo
data:
  default.conf: |
    server {
      listen 80;
      location / {
        return 200 "Hello from NGINX Pod: $hostname\n";
      }
    }
---
# =========================
# Secret（今回はダミー）
# =========================
apiVersion: v1
kind: Secret
metadata:
  name: nginx-secret
  namespace: nginx-demo
type: Opaque
stringData:
  dummy-password: secret123
---
# =========================
# Deployment（Podを3つ）
# =========================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: nginx-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.25
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-config
---
# =========================
# Service（ロードバランサ）
# =========================
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: nginx-demo
spec:
  type: ClusterIP
  selector:
    app: nginx
  ports:
  - port: 80
    targetPort: 80
---
# =========================
# Ingress（外部公開）
# =========================
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
  namespace: nginx-demo
spec:
  rules:
  - host: nginx.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx-service
            port:
              number: 80
---
# =========================
# HPA（オートスケール）
# =========================
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: nginx-hpa
  namespace: nginx-demo
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nginx-deployment
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
---
# =========================
# PodDisruptionBudget
# =========================
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: nginx-pdb
  namespace: nginx-demo
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: nginx
